felixguendling/cista

include/cista/serialization.h, include/cista/serialized_size.h, include/cista/targets/buf.h, include/cista/targets/file.h
=> use serialized_size<T>() in serialization targets (buf, file)

CMake/cistaConfig.cmake.in, CMakeLists.txt
Install target pretty much copied from Catch2 CMakeLists.txt - only triggers when Cista is not included via `add_subdirectory`.
Also creates a `cista::cista` namespaced target as per CMake convention.
=> Create an install target

include/cista/containers/hash_storage.h, include/cista/containers/offset_ptr.h, include/cista/containers/unique_ptr.h
Certainly noexcept:
Unsure if noexcept:
Noexcept depends on the contained elements:
~~variant~~ **not implemented in this PR**
=> mark move_ctor and move_assign as noexcept

include/cista/mmap.h
The `file_mapping_` handle was not moved, which results in a crash in the destructor when trying to close the invalid handle.
=> fix mmap move constructor + assignment for windows

include/cista/containers/vector.h
This changes vector to use memcpy for trivially copyable types when copying a vector. For large vectors (several hundred MB/GB), this is ~2x faster on my machine (MSVC).
=> vector: use memcpy for trivially copyable types

test/vector_test.cc
See the two added tests. The first one passes as expected. The second one fails. 
Might be related, but I don't think neither of the two erase functions in basic_vector ensure that https://github.com/felixguendling/cista/blob/eb1b0199eef401493db0d2dd735a14481b823083/include/cista/serialization.h#L657 or similar are satisfied.
=> Fails to serialize when entire vector contents are erased

tools/pretty-printers/gdb/cista_hash_storage.py, tools/pretty-printers/gdb/cista_pointer.py, tools/pretty-printers/gdb/cista_string.py, tools/pretty-printers/gdb/cista_tuple.py, tools/pretty-printers/gdb/cista_variant.py, tools/pretty-printers/gdb/cista_vector.py, tools/pretty-printers/gdb/offset_pointer.py
This pull request contains pretty printers for some of the cista containers. These are implented using the Python API from GDB. These help when debugging programs that use cista containers by making them easier to inspect directly with GDB or in an IDE like CLion. 
With the exception of hash_storage (for the map and the set) the rest should be also be straightforward to implement. I haven't had a closer look at hash_storage yet.
In general these are build to be used with CLion (or any other IDE that uses the same protocols). The straight text output is very basic / unchanged, since CLion does not seem to care about it.
The current implementation might can be improved by removing levels indirections to make the pretty output even prettier and porting / reimplementing these for LLDB.
=> Pretty Printers for Cista

tools/pretty-printers/gdb/cista_hash_storage.py, tools/pretty-printers/gdb/cista_pointer.py, tools/pretty-printers/gdb/cista_string.py, tools/pretty-printers/gdb/cista_tuple.py, tools/pretty-printers/gdb/cista_variant.py, tools/pretty-printers/gdb/cista_vector.py, tools/pretty-printers/gdb/offset_pointer.py
They would not work on const and/or volatile types otherwise. Now they do.
=> Fix pretty printers

include/cista/memory_holder.h
`byte_buf` (`std::vector<uint8_t>`) is returned by `cista::serialize`.
MOTIS uses `memory_holder` to store data. Adding `byte_buf` allows easy data duplication by serializing and deserializing the data without the need to make a copy of the buffer.
=> add byte_buf to memory_holder variant

include/cista/containers/bitvec.h
in bitvec the blocks_.size() is not known at compile time.
=> remove constexpr from bitvec shift

include/cista/containers/optional.h, include/cista/serialization.h
fixes two bugs with cista::optional when wrapping types with non-trivial copy/move operations (e.g. offset::ptr).
1. call copy/move constructors/assignment operators explicitly for types with non-trivial copy/move operations.
2. use the serialization overload for the wrapped typed instead of the generic optional storage
=> fix optional

include/cista/containers/unique_ptr.h
Hello!
While I was running asan and tsan tests on my project, I met a memory leak. It took me a while, but I found the culprit ! I think cista definitely needs to have its tests run with the address sanitizer.
Now that I think about it: maybe it's worth specialising `std::swap` for cista's classes.
Adel
=> basic_unique_ptr: reset on move assignment

include/cista/containers/string.h
The two added constructors are necessary for the following constructors to work:
* basic_string(char const* s, typename base::msize_t const len)
* basic_string_view(char const* s, typename base::msize_t const len)
=> add missing generic_string constructors

include/cista/serialization.h, include/cista/type_hash/static_type_hash.h
Hello!
Hope you are doing well, during some of my internal tests, I realized `cista` wasn't throwing when trying to deserialize a type `T1` as a type `T2`, which were related but not the same: one contained many elements of the second, something like
```c++
struct T1
{
int a;
}
struct T2
{
T1 a,b,c,d,e,f;
}
```
and I found two things to fix, so here you go!
Adel
=> static type hash small fixes

include/cista/containers/offset_ptr.h
Fixes compilation using MSVC 17.7 if `/Zc:__cplusplus` is not set
=> offset_ptr: fix __cplusplus check for msvc

include/cista/containers/string.h, include/cista/hashing.h, include/cista/type_traits.h
This commit adds cista/type_traits.h and move is_char_array_helper and is_string_helper into that new header file.
=> type_traits: Separate type traits helpers into a new header file

include/cista/containers.h, include/cista/containers/cstring.h, include/cista/hashing.h, include/cista/serialization.h, test/cstring_serialize_test.cc, test/cstring_test.cc
This new type is able to store a trailing \0 character, without compromising one byte for storage when the string is a small-string.
Storage of NUL character within data is also supported.
This is inspired by
https://github.com/felixguendling/cista/issues/187#issuecomment-1603128882.
See https://github.com/felixguendling/cista/issues/187.
=> RFC: Add cista::*::cstring type

include/cista/aligned_allocator.h, include/cista/cista_exception.h, include/cista/containers/cstring.h, include/cista/containers/hash_storage.h, include/cista/containers/mutable_fws_multimap.h, include/cista/containers/optional.h, include/cista/containers/string.h, include/cista/containers/variant.h, include/cista/containers/vector.h, include/cista/exception.h, include/cista/serialization.h, include/cista/targets/file.h, include/cista/verify.h
This change introduces cista::throw_exception as a helper to dispatch the call to either a throw expression, or abort() call in case -fno-exception is enabled.
=> Allow the library to be used in -fno-exception targets

include/cista/containers/hash_storage.h
The assignment operator of hash_storage now calls the `clear` function to ensure proper behavior. Previously, it only cleared the destination hash_storage if the source hash_storage was empty, leading to keys being left in the destination hash_storage that did not exist in the source, and not being copied if they already exist in the destination hash_storage. Now, the assignment operator clears the destination hash_storage every time, preventing this issue.
=> hash_storage: fix assignment operator

include/cista/containers/hash_storage.h
Resolves #214
The equality operator for hash maps should compare both keys and mapped values, not just the keys.
=> hash_storage: compare values in equality operator

include/cista/containers/optional.h
Besides calling has_value() to check if the container contains anything, if (opt) pattern can be used as well.
=> cista::optional: add bool conversion operator

include/cista/containers/string.h, include/cista/next_power_of_2.h, test/string_test.cc
performs a simple way to check if a string has prefix/suffix
add test cases for starts_with and ends_with
fix wrong sizeof comparison for 64-bit integers
add sizeof comparisons for 16 and 32-bit integers
=> fix next_power_of_two and improve generic_string

include/cista/containers/bitvec.h
- Fix a crash in `count()` if the bitvec is empty (invalid memory access in `sanitized_last_block()`)
- Fix compilation error in `set(std::string_view)` if `size_type != std::size_t`
- Remove constexpr from `set(std::string_view)` and `basic_bitvec(std::string_view)` because the used `resize` function isn't constexpr
=> bitvec fixes

.github/workflows/linux.yml, include/cista/containers/string.h, include/cista/serialization.h, test/cstring_serialize_test.cc
- Linux: update deprecated upload-artifact version to prevent automatic build failure
- fix missing endian conversion during (de-)serialization
- ensure short string alignment
=> Update workflow and fix endian conversion and alignment in cista::generic_string

include/cista/containers/vector.h, include/cista/containers/vecvec.h, test/vecvec_test.cc
Offers a method to enlarge a `basic_vecvec::bucket`, which is needed in some use cases.
Currently this is only possible by multiple calls to `bucket::push_back()`, which isn't great when inserting many elements.
=> Add method to enlarge basic_vecvec::bucket

include/cista/containers/bitvec.h
Adds a new `one_out()` function to `bitvec` that sets all bits to one (similar to the already existing `zero_out`).
=> bitvec: add one_out()

include/cista/containers/cstring.h
For reference: https://cplusplus.com/reference/string/string/c_str/
Just a convenience method, but it's one I used in the std lib and it was a hassle to remove every call to it when I switched to Cista strings.
=> Add c_str method to string to match std::string

include/cista/containers/vector.h
Currently, `vector<T>.resize(size)` and `vector<T>(size)` require `T` to have a copy constructor, making these functions impossible to use with types such as `std::unique_ptr`.
This PR splits `resize` and the constructor with a size argument into two functions to fix this issue.
=> fix vector.resize for types without copy constructor

include/cista/containers/vector.h
Hi,
this tiny PR would bring cista::basic_vector a little closer to the `std::vector` interface by adding
- a missing r-value accepting [push_back(T&&)](https://en.cppreference.com/w/cpp/container/vector/push_back) overload
- a no-op [shrink_to_fit](https://en.cppreference.com/w/cpp/container/vector/shrink_to_fit)
Particularly, the shrink-to-fit function being a no-op is explicitly allowed by the standard as an implementation choice for std::vector. 
The lack of these two functions has posed a problem to me when using cista with some 3rd-party libraries. Let me know if you want something changed!
=> add push_back(T&&) overload and no-op shrink_to_fit in basic_vector

include/cista/containers/vecvec.h
MSVC needs this static_cast to compile MOTIS
=> vecvec: add static_cast for msvc

include/cista/targets/file.h
Currently, using r+ mode with open_file on Windows causes the file content to be erased. 
To prevent this, OPEN_ALWAYS should be used instead.
=> Fix: Prevent file content loss when using r+ mode on Windows

include/cista/atomic.h, include/cista/containers/bitvec.h, include/cista/hashing.h, test/atomic_test.cc, test/bitvec_test.cc
based on UB - don't use without testing for your compiler + platform
will be replaced by `std::atomic_ref` as soon as available
=> atomic fetch_or, fetch_and, fetch_min, fetch_max

include/cista/containers/vector.h
Move-assignment with the rvalue reference to the object itself should be no-op.
=> vector: fix move-assignment

include/cista/containers/cstring.h, include/cista/containers/vector.h
For cstring:
- reset() needs to be called when doing a move-assignment.
For vector:
- set() needs to call clear() to destroy the existing objects.
=> cstring, vector: fix memory leaks

include/cista/hashing.h
negative floating point -> signed int is well defined, signed int -> unsigned int is well defined. direct cast is not.
Advantage: changed hashes only for signed floating points, probably in most cases not even that.
Alternative: std::bit_cast -> C++20. std::memcpy -> not constexpr.
=> fix signed scalar hash

include/cista/containers/variant.h
Return a value for the function visit, and since function apply accepts a right-value reference, use std::forward for perfect forwarding.
=> fix the std::visit should return a value (#248)
